# Main configuration for RL Traffic Control
project:
  name: "rl-traffic-control"
  version: "0.1.0"
  
sumo:
  binary: "sumo"
  gui: false
  step_length: 1.0
  max_steps: 3600
  
training:
  algorithm: "PPO"
  episodes: 1000
  learning_rate: 0.0003
  batch_size: 64
  
environment:
  observation_space: "phase_duration"
  action_space: "discrete"
  reward_function: "queue_length"
  
ray:
  num_workers: 4
  num_gpus: 0
  
logging:
  level: "INFO"
  tensorboard: true
  save_frequency: 100